apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bitroid-dev
  name: restapi
  annotations: {}
spec:
  selector:
    matchLabels:
      app: restapi
  replicas: 1
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - name: container
          image: 'quay.io/hemanth22/restapi:feature_logger'
          ports:
            - containerPort: 8080
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
