apiVersion: v1
kind: Service
metadata:
  name: restapi-service
  namespace: bitroid-dev
spec:
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
