# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "batchjob" ]
  pull_request:
    branches: [ "batchjob" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download Openshift client
        run: curl -O https://downloads-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/amd64/linux/oc.tar
      # Runs a set of commands using the runners shell
      - name: verify openshift client version
        run: |
          echo "[Github Task 1] Untar oc cli"
          tar -xvf oc.tar
          echo "[Github Task 2] Openshift cli version"
          ./oc version
          ls -ltr

      - name: Openshift Deployment
        run: |
          echo "[Github Task 1] Openshift login"
          ./oc login --token="$OPENSHIFT_PASSWORD" --server="$OPENSHIFT_SERVER"
          echo "[Github Task 2] Openshift fetch projects"
          ./oc project
          echo "[Github Task 3] Delete existing deployed batchjob"
          ./oc delete -f ./batchjob_python.yaml
          echo "[Github Task 4] Deployment of batchjob"
          ./oc create -f ./batchjob_python.yaml
          sleep 30
          echo "[Github Task 5] Openshift CLI get batchjobs"
          ./oc get jobs
          sleep 60
          echo "[Github Task 6] Openshift CLI get logs batchjobs"
          ./oc logs jobs/pythonbatchjob
          sleep 10
          ./oc get jobs
          ./oc logout
        env: 
          OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
